### ISSUE TITLE
为什么测试集里面的标题只有三条啊？还是我理解有问题？

### ISSUE THREAD

**Issue by shuaizhao95** [CLUEbenchmark/CLGE#10]
![image](https://user-images.githubusercontent.com/45233543/105579856-02fc6280-5dc4-11eb-8949-6bfbab47c36e.png)
![image](https://user-images.githubusercontent.com/45233543/105579862-0bed3400-5dc4-11eb-9c7b-93f111f6a3d9.png)
十分困惑，为什么test数据集中没有标准摘要，怎么进行测评啊？

**Comment by ydli-ai** [comment]
目前的测试集不包含标签，之后会支持在线验证。
