### ISSUE TITLE
lcsts任务中如何保存keras模型到checkpoint pb模型

### ISSUE THREAD

**Issue by iamownt** [CLUEbenchmark/CLGE#7]
lcsts的生成中run_roberta_wwm_ext.sh中 最后model.fit_generator生成效果很好，但是怎么保存模型呢，keras模型只能保存成h5，hdf5模式，但是如果训练一段时间，想要保存checkpoint怎么办？谢谢！！

**Comment by iamownt** [comment]
使用mode.save_weights即可。

**Comment by OrangeInSouth** [comment]
想请问一下如何保存成RoBERTa-wwm那样，包含index，data和meta三个文件呢？

**Comment by iamownt** [comment]
> 想请问一下如何保存成RoBERTa-wwm那样，包含index，data和meta三个文件呢？
只能退一步保存weights文件，先导入checkpoint了。bert4keras已经改了很多版本了，这是很旧的版本了。

**Comment by OrangeInSouth** [comment]
👌，谢谢
